In [1]:
! cat /proc/meminfo

MemTotal:       16513336 kB
MemFree:         8782916 kB
HighTotal:             0 kB
HighFree:              0 kB
LowTotal:       16513336 kB
LowFree:         8782916 kB
SwapTotal:       1048576 kB
SwapFree:         938152 kB


In [22]:
print (type(1.5))

<class 'float'>


In [11]:
import pandas as pd

df = pd.read_csv('creditcard.csv')
df.head()
print("Null value in the dataframe")
# df.isnull()
# df.isnull().sum()
# df.isnull()
# df.isnull().any()
# print(df.tail())

Null value in the dataframe


In [29]:
superhero = "Iron, man"
print(superhero)

Iron, man


In [30]:
num1 = int(input("Entre the value: "))
num2 = int(input("Entre the value: "))

sum = num1 + num2
print(sum)


Entre the value:  49
Entre the value:  2


51


In [1]:
number = [50, 100, 150, 200]

for i in number:
    print(i)

50
100
150
200


In [ ]:
i = 0

while i< 10:
    print(i)
    i += 1
    print("True")

In [30]:
import math

num = int(input("Enter the number: "))

factorial = math.factorial(num)

print(num, "Fact", factorial)


Enter the number:  5


5 Fact 120


In [4]:
number = int(input("Enter the number: "))

factorial = 1

if number == 0:
    print("The factorial is 0 is 1")

else:
    for i in range (1, number + 1):
      factorial = factorial * i
print('The factorial of given number is: ', number,'is', factorial)

Enter the number:  10


The factorial of given number is:  10 is 3628800


In [30]:
# Factorial function

def factorial_value(num):
  factorial = 1

  if num == 0:
      return factorial

  else:
    for i in range (1, num+1):
         factorial = factorial * i
    return factorial        
    

In [47]:
print(factorial_value(6))

720


In [32]:
print(factorial_value(5))

120


In [5]:
import numpy as np

In [7]:
# List vs Numpy - time takin 
from time import process_time 

#Time taken by a list 

In [9]:
python_list = [i for i in range(10000)] 
start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [13]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +- 5

end_time = process_time()

print(end_time - start_time)


0.0


In [14]:
# Numpy Array

list = [1,2,3,4,5]
print(list)
print(type(list))


[1, 2, 3, 4, 5]
<class 'list'>


In [32]:
np_array = np.array([1,2,3,4,5,])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [33]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [34]:
b.shape

(2, 4)

In [36]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [38]:
# initial Placeholder in numpy array 
# create a numpy array of zeros 

x = np.zeros((4,5))
print(x)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [42]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [45]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [46]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
# createa  numpy array with random value
b = np.random.random((3,4))
print(b)

[[0.48892005 0.73633221 0.58062295 0.70142824]
 [0.32376271 0.69046212 0.29312185 0.37610522]
 [0.49154622 0.17078892 0.28497199 0.96955536]]


In [48]:
# random interger values array with a specific range 
c = np.random.randint(10,100,(3,5))
print(c)

[[83 16 65 77 53]
 [72 26 22 66 40]
 [30 28 38 25 62]]


In [55]:
# array of every spaced values  --> specifying the number of value required 
d = np.linspace(10,30,6)
print(d)


[10. 14. 18. 22. 26. 30.]


In [57]:
#array of evelny space value  --> specifying the step

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [58]:
# convert a list to array 
list2 = [10,20, 30, 40]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

In [59]:
# Analysing a numpy array 

c = np.random.randint(10,90,(5,5))
print(c)

[[18 10 76 32 57]
 [32 14 89 51 15]
 [54 24 13 29 33]
 [87 20 40 61 88]
 [67 60 16 56 34]]


In [60]:
# Array dimension 
print(c.shape)

(5, 5)


In [62]:
# number of dimension 
print(c.ndim)

2


In [63]:
# number of element in an array 
print(c.size)


25


In [65]:
# checking the data type in the value in the array 
print(c.dtype)

int32


In [66]:
# Mathemitical operation on a np array

In [69]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or join two list 


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [79]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[0 2 7]
 [8 2 4]
 [7 1 7]]
[[13 17 16]
 [12 12 12]
 [18 10 10]]


In [83]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[13 19 23]
 [20 14 16]
 [25 11 17]]
[[-13 -15  -9]
 [ -4 -10  -8]
 [-11  -9  -3]]
[[  0  34 112]
 [ 96  24  48]
 [126  10  70]]
[[0.         0.11764706 0.4375    ]
 [0.66666667 0.16666667 0.33333333]
 [0.38888889 0.1        0.7       ]]


In [84]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [86]:
print(a)
print(b)

[[4 0 3]
 [6 5 3]
 [0 4 2]]
[[19 11 12]
 [18 13 14]
 [11 16 17]]


In [88]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[23 11 15]
 [24 18 17]
 [11 20 19]]
[[-15 -11  -9]
 [-12  -8 -11]
 [-11 -12 -15]]
[[ 76   0  36]
 [108  65  42]
 [  0  64  34]]
[[0.21052632 0.         0.25      ]
 [0.33333333 0.38461538 0.21428571]
 [0.         0.25       0.11764706]]


In [89]:
# Array Manuplations 

In [91]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 3 0]
 [0 2 6]]
(2, 3)


In [93]:
# transpose 
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 0]
 [3 2]
 [0 6]]
(3, 2)


In [95]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 3 9]
 [1 9 7]]
(2, 3)


In [97]:
 trans2 = array.T
print(trans)
print(trans2.shape)

[[2 0]
 [3 2]
 [0 6]]
(3, 2)


In [99]:
# reshaping a array 
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 9 3]
 [6 5 9]]
(2, 3)


In [101]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 9]
 [3 6]
 [5 9]]
(3, 2)
